"""empty message

Revision ID: f65fa78b814a
Revises: 
Create Date: 2020-05-31 15:01:06.830644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65fa78b814a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Elderlies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('contact1', sa.Integer(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Groceries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groceries', sa.Text(), nullable=True),
    sa.Column('elderly_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['elderly_id'], ['Elderlies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Helpers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('contact1', sa.Integer(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('elderly_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['elderly_id'], ['Elderlies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Helpers')
    op.drop_table('Groceries')
    op.drop_table('Elderlies')
    # ### end Alembic commands ###
